version: '3'
services:
  jupyter:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    volumes:
      - "C:/PersonalRepos/my-life-data/analysis:/home/jovyan/work"       # Caminho absoluto para a pasta de notebooks
      - "C:/PersonalRepos/my-life-data/data/movies:/home/jovyan/movies"  # Caminho absoluto para a pasta de arquivos .csv
    environment:
      JUPYTER_TOKEN: "meutoken"

