version: '3'
services:
  jupyter:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    volumes:
      - "../analysis:/home/jovyan/work"
      - "../data:/home/jovyan/data"
    environment:
      JUPYTER_TOKEN: "meutoken"
