name: Update life summary

on:
  push:
    branches:
      - main
      - master

jobs:
  run-summary-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run life summary script
        run: python update_life_summary.py

      - name: Ensure repository is clean
        run: git diff --exit-code
